#!/bin/sh

if [[  ! -f "/var/log/nginx/error.log"  ]]; then 
	mkdir -p /var/log/nginx
	touch /var/log/nginx/error.log
	chown npuser:nginx -R /var/log/nginx
	chmod 775 -R /var/log/nginx
fi

if [[  ! -f "/app/log/nginx/error.log"  ]]; then 
	mkdir -p /app/log/nginx
	touch /app/log/nginx/error.log
	chown npuser:nginx -R /app/*
	chmod 775 -R /app/*
fi

if [[  ! -d "/tmp/nginx/client-body"  ]]; then
	mkdir -p /tmp/nginx/client-body
	chown npuser:nginx -R /tmp/nginx/client-body
	chmod 775 -R /tmp/nginx/client-body
fi

exec su -l npuser -c "/usr/sbin/nginx -c /etc/nginx/nginx.conf"
