#!/bin/sh

if [[  ! -f "$home/log/nginx/error.log"  ]]; then 
	su -l $user -c "mkdir -p $home/log/nginx && touch $home/log/nginx/error.log"
fi
if [[  ! -d '/tmp/nginx/client-body'  ]]; then
	mkdir -p /tmp/nginx/client-body
fi

exec /usr/sbin/nginx -c /etc/nginx/nginx.conf