#!/bin/sh

if [[  ! -f "/app/log/nginx/error.log"  ]]; then 
	su -l $user -c "mkdir -p /app/log/nginx && touch /app/log/nginx/error.log"
fi
if [[  ! -d "/tmp/nginx/client-body"  ]]; then
	mkdir -p /tmp/nginx/client-body
fi

exec /usr/sbin/nginx -c /etc/nginx/nginx.conf