#!/bin/sh

if [[  ! -d '/var/run/php-fpm'  ]]; then mkdir -p /var/run/php-fpm; fi
if [[  ! -d "$home/log/php"  ]]; then mkdir -p $home/log/nginx; fi

exec /usr/bin/php-fpm -c /etc/php/php.ini -y /etc/php/php-fpm.conf
